# Generated by Django 5.0.1 on 2024-01-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0002_rename_shifts_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
