# Generated by Django 5.0.1 on 2024-01-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0004_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Caretaker',
        ),
    ]
