# Generated by Django 5.0.1 on 2024-01-31 17:59

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0007_alter_caregiver_first_name_alter_caregiver_surname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shift',
            managers=[
                ('activities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregiver.shift')),
            ],
        ),
    ]
