# Generated by Django 5.0.2 on 2024-02-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0009_rename_date_shift_date_of_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 13, 37, 31, 920504)),
        ),
    ]
