# Generated by Django 5.0.2 on 2024-03-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0010_caregiver_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='surname',
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 15, 20, 39, 48, 291174)),
        ),
    ]
