# Generated by Django 4.2.8 on 2024-02-16 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0011_alter_caregiver_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 16, 12, 48, 26, 802665)),
        ),
    ]
