# Generated by Django 5.0.2 on 2024-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0012_alter_caregiver_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='start_date',
            field=models.DateField(),
        ),
    ]
