# Generated by Django 5.0.2 on 2024-03-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0013_alter_caregiver_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='start_date',
        ),
    ]
