# Generated by Django 5.0.2 on 2024-04-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0014_remove_caregiver_start_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shift',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
