# Generated by Django 5.0.1 on 2024-01-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0003_delete_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('date', models.DateField()),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caretaker.caretaker')),
            ],
        ),
    ]
