# Generated by Django 5.0.2 on 2024-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_address_zip_code_alter_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
    ]
