# Generated by Django 5.0.2 on 2024-04-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('birthday', models.DateField()),
                ('health_info', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=50)),
                ('when', models.CharField(choices=[('rano', 'Ráno'), ('v poledne', 'V poledne'), ('vecer', 'Večer'), ('v noci', 'V noci'), ('jine', 'Jiné')], max_length=20)),
                ('how', models.CharField(choices=[('pred jidlem', 'před jídlem'), ('s jidlem', 's jídlem'), ('po jidle', 'po jídle'), ('jine', 'jiné')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('syn/dcera', 'Syn/Dcera'), ('pritel/kyne', 'Přítel/kyně'), ('sourozenec', 'Sourozenec'), ('rodic', 'Rodič'), ('manzel/ka', 'Manžel/ka'), ('jini pribuzni', 'Jiní příbuzní'), ('jine', 'Jiné')], max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
