# Generated by Django 5.0.1 on 2024-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=50)),
                ('when', models.CharField(choices=[('rano', 'Ráno'), ('v poledne', 'V poledne'), ('vecer', 'Večer'), ('v noci', 'V noci'), ('jine', 'Jiné')], default='-', max_length=20)),
                ('how', models.CharField(choices=[('pred jidlem', 'Před jídlem'), ('s jídlem', 'S jídlem'), ('po jidle', 'Po jidle'), ('jine', 'Jiné')], default='-', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='fav_activities',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='health_info',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(choices=[('pritel/kyne', 'Přítel/kyně'), ('sourozenec', 'Sourozenec'), ('rodic', 'Rodič'), ('manzel/ka', 'Manžel/ka'), ('jine', 'Jiné')], default='-', max_length=20),
        ),
    ]
