# Generated by Django 5.0.1 on 2024-01-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_medicationintake_patient_fav_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationintake',
            name='patient',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(choices=[('pritel/kyne', 'Přítel/kyně'), ('sourozenec', 'Sourozenec'), ('rodic', 'Rodič'), ('manzel/ka', 'Manžel/ka'), ('jini pribuzni', 'Jiní příbuzní'), ('jine', 'Jiné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='how',
            field=models.CharField(choices=[('pred jidlem', 'Před jídlem'), ('s jídlem', 'S jídlem'), ('po jidle', 'Po jídle'), ('jine', 'Jiné')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='when',
            field=models.CharField(choices=[('rano', 'Ráno'), ('v poledne', 'V poledne'), ('vecer', 'Večer'), ('v noci', 'V noci'), ('jine', 'Jiné')], max_length=20),
        ),
    ]
