# Generated by Django 5.0.2 on 2024-02-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patient_first_name_alter_patient_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 13, 37, 31, 936132)),
        ),
    ]
