# Generated by Django 5.0.2 on 2024-02-11 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 13, 53, 21, 295521)),
        ),
    ]
