# Generated by Django 5.0.2 on 2024-03-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patient_first_name_remove_patient_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(choices=[('syn/dcera', 'Syn/Dcera'), ('pritel/kyne', 'Přítel/kyně'), ('sourozenec', 'Sourozenec'), ('rodic', 'Rodič'), ('manzel/ka', 'Manžel/ka'), ('jini pribuzni', 'Jiní příbuzní'), ('jine', 'Jiné')], max_length=20),
        ),
    ]
