# Generated by Django 5.0.2 on 2024-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_contact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateField(),
        ),
    ]
