# Generated by Django 5.0.2 on 2024-04-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patient', '0011_alter_patient_fav_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fav_activities',
        ),
        migrations.AddField(
            model_name='patient',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
